### ISSUE TITLE
I am facing issues while installing jdbc

### ISSUE THREAD

**Issue by MadhukumarB** [CraZySacX/node-jdbc#54] opened 2015-09-03 06:30 UTC
C:\Users\GNTM84>npm install -g jdbc
-
> java@0.5.5 install C:\Users\GNTM84\AppData\Roaming\npm\node_modules\jdbc\node_
modules\java
> node-gyp rebuild

C:\Users\GNTM84\AppData\Roaming\npm\node_modules\jdbc\node_modules\java>if not d
efined npm_config_node_gyp (node "C:\Program Files (x86)\nodejs\node_modules\npm
\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else
(node  rebuild )
[node-java] Error: Command failed: C:\windows\system32\cmd.exe /s /c "reg query
"hklm\software\javasoft\java development kit""
ERROR: The system was unable to find the specified registry key or value.

Error: Command failed: C:\windows\system32\cmd.exe /s /c "reg query "hklm\softwa
re\wow6432node\javasoft\java development kit""
ERROR: The system was unable to find the specified registry key or value.

gyp: Call to 'node findJavaHome.js' returned exit status 1. while trying to load
 binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (C:\Program Files (x86)\nodejs\node_
modules\npm\node_modules\node-gyp\lib\configure.js:355:16)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1074
:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files (x86)\\nodejs\\node_modules\\npm\\nod
e_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\GNTM84\AppData\Roaming\npm\node_modules\jdbc\node_modules\
java
gyp ERR! node -v v0.12.7
gyp ERR! node-gyp -v v2.0.1
gyp ERR! not ok
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program Files (
x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "jdbc"
npm ERR! node v0.12.7
npm ERR! npm  v2.11.3
npm ERR! code ELIFECYCLE

npm ERR! java@0.5.5 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the java@0.5.5 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the java package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls java
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\GNTM84\npm-debug.log

Could you please let me know what can be done to fix this.This is the major part in my project.I am totally stuck now.

I reinstalled every thing but still facing the same issue.Really frustrated

Also please let us know if there are any dependencies for installing jdbc module.

**Comment by CraZySacX** [comment] 2015-09-03 13:16
The problem is with node-java (a dependency of node-jdbc).  

```Call to 'node findJavaHome.js' returned exit status 1. while trying to load binding.gyp```

This error indicates that node-java cannot find your JAVA_HOME directory.  Ensure you have Java installed and the JAVA_HOME directory installed correctly.  You may want to head over to the [node-java](https://github.com/joeferner/node-java) issues list and look there for a solution as well.

**Comment by MadhukumarB** [comment] 2015-09-14 17:39
Hi,

I can able to install the JDBC module now but when i run my app.js file, It is throwing the below error.

 Object #<JDBC> has no method 'open'
    at exports.list (/home/user/RedshiftAPIDOC/routes/user.js:74:13)
    at callbacks (/home/user/RedshiftAPIDOC/node_modules/express/lib/router/index.js:161:37)
    at param (/home/user/RedshiftAPIDOC/node_modules/express/lib/router/index.js:135:11)
    at pass (/home/user/RedshiftAPIDOC/node_modules/express/lib/router/index.js:142:5)
    at Router._dispatch (/home/user/RedshiftAPIDOC/node_modules/express/lib/router/index.js:170:5)
    at Object.router (/home/user/RedshiftAPIDOC/node_modules/express/lib/router/index.js:33:10)
    at next (/home/user/RedshiftAPIDOC/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.methodOverride [as handle] (/home/user/RedshiftAPIDOC/node_modules/express/node_modules/connect/lib/middleware/methodOverride.js:37:5)
    at next (/home/user/RedshiftAPIDOC/node_modules/express/node_modules/connect/lib/proto.js:190:15)
    at Object.jsonParser [as handle] (/home/user/RedshiftAPIDOC/node_modules/body-parser/lib/types/json.js:100:40)
Mon, 14 Sep 2015 17:22:28 GMT uncaughtException: object is not a function
TypeError: object is not a function
    at /home/user/RedshiftAPIDOC/node_modules/jdbc/lib/pool.js:74:12
    at /home/user/RedshiftAPIDOC/node_modules/jdbc/node_modules/async/lib/async.js:52:16
    at /home/user/RedshiftAPIDOC/node_modules/jdbc/node_modules/async/lib/async.js:363:13
    at /home/user/RedshiftAPIDOC/node_modules/jdbc/node_modules/async/lib/async.js:52:16
    at done (/home/user/RedshiftAPIDOC/node_modules/jdbc/node_modules/async/lib/async.js:243:17)
    at /home/user/RedshiftAPIDOC/node_modules/jdbc/node_modules/async/lib/async.js:44:16
    at /home/user/RedshiftAPIDOC/node_modules/jdbc/node_modules/async/lib/async.js:360:17
    at /home/user/RedshiftAPIDOC/node_modules/jdbc/lib/pool.js:68:7
    at /home/user/RedshiftAPIDOC/node_modules/jdbc/lib/pool.js:19:14
    at /home/user/RedshiftAPIDOC/node_modules/jdbc/lib/drivermanager.js:21:18

User.js file where i an initializing the jdbc connection and opening the connection is


/*
 * GET users list.
 */
var jdbc = require('jdbc');
var express = require('express');
var config=require('./config');
var Queries=require('./Queries');
exports.list = function(req, res){
	
	//console.log("config:"+config);
	var redshiftDB=new jdbc(config);
	redshiftDB.initialize(config, function(err, res) {

	    console.log("Connection opened successfully!");


	    if (err) {

	        console.log(err);
	    }

	});




	redshiftDB.open(function(err, conn) {
		 if (conn) {
		// SELECT statements are called with executeQuery 
			 redshiftDB.executeQuery(Queries.Api1_query, function(err, results) {
			if (err) {
				 console.log(err);
				} else if (results) {
				  console.log(results);
				  res.type('text/plain'); 			// set content-type
		          res.send(results); 	
				}

			redshiftDB.close(function(err) {
				if(err) {
				  console.log(err);
				} else {
				  console.log("Connection closed successfully!");
				}
				});

				}
);
		 }
		});
 // res.send("respond with a resource");
};

Could you please let me know why am i getting this error.

The same code is working in my local

**Comment by CraZySacX** [comment] 2015-09-14 17:50
What version of node-jdbc are you using?

Based on the error output (references to pool.js), I believe that you are using the newer version of node-jdbc with the old API calls.  Check out the [README.md](https://github.com/CraZySacX/node-jdbc) and the [tests](https://github.com/CraZySacX/node-jdbc/blob/master/test/test-derby.js) for example usage of the new API.

**Comment by CraZySacX** [comment] 2015-09-25 17:28
Closing this as newer issue indicates that node-jdbc is installed now.

**Closed by CraZySacX** 2015-09-25 17:28 UTC
