### ISSUE TITLE
Java Runtime Environment fatal error

### ISSUE THREAD

**Issue by vahaknp** [CraZySacX/node-jdbc#56] opened 2015-09-11 22:02 UTC
```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000000104310bde, pid=19077, tid=1299
#
# JRE version: Java(TM) SE Runtime Environment (7.0_80-b05) (build 1.7.0_80-ea-b05)
# Java VM: Java HotSpot(TM) 64-Bit Server VM (24.80-b07 mixed mode bsd-amd64 compressed oops)
# Problematic frame:
# V  [libjvm.dylib+0x310bde]
#
# Failed to write core dump. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again
#
# An error report file with more information is saved as:
# /Users/vahakn/Sites/gk-follower-backend/hs_err_pid19077.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```

This error occasionally comes up when querying Impala using the new jdcb version. The queries I had been using before the patch remain unchanged. Any idea what the issue might be or what the best way to debug would be?

Thanks!

**Comment by CraZySacX** [comment] 2015-09-12 01:19
Some googling of that error led to these:

http://stackoverflow.com/questions/25874436/sigsegv-while-running-run-app-on-grails-2-4-3
http://stackoverflow.com/questions/6448163/a-fatal-error-has-been-detected-by-the-java-runtime-environment-sigsegv-libjvm

In both cases it was caused by failing memory on the system.

**Comment by CraZySacX** [comment] 2015-09-25 17:52
If this happens again could you supply the err report.

In the issue above it's located at ```/Users/vahakn/Sites/gk-follower-backend/hs_err_pid19077.log```

**Comment by CraZySacX** [comment] 2015-10-12 19:29
Closing for now.  Feel free to reopen if this is continuing.

**Closed by CraZySacX** 2015-10-12 19:29 UTC
