### ISSUE TITLE
node-jdbc automatically uninstalling

### ISSUE THREAD

**Issue by KalaiselvanMahendran** [CraZySacX/node-jdbc#157] opened 2018-01-05 04:45 UTC
Hi,

After installing the node-jdbc module in my application, if I install new npm module JDBC module automatically getting removed from the node_modules folder.

How to solve this issue @CraZySacX

**Comment by CraZySacX** [comment] 2018-01-05 19:51
Did you install it with npm i --save?   If it isn't persisted in your package.json, the auto-pruning may remove it.   It's that's not the case, I'm not sure why it would be disappearing.

**Comment by CraZySacX** [comment] 2018-01-08 12:48
Closing.  Feel free to re-open if you think this is caused by node-jdbc.

**Closed by CraZySacX** 2018-01-08 12:48 UTC
