### ISSUE TITLE
Upgrade 0.0.13-->0.0.15. Connect to Hive/Impala: NullPointerException

### ISSUE THREAD

**Issue by veve90** [CraZySacX/node-jdbc#68] opened 2015-09-28 09:33 UTC
Hello,

Before we used the 0.0.13 version in order to connect to to impala and hive.
We tried to upgrade to 0.0.15 (no changes needed for the code) but with this version we cannot connect to Impala:

```
nullPointerException:
java.lang.NullPointerException
	at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:133)
	at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:105)
	at java.sql.DriverManager.getConnection(DriverManager.java:664)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)

```
Thank you!

**Comment by CraZySacX** [comment] 2015-09-28 13:33
Can you share your config code?   Hard to tell what's going on without it.

**Comment by veve90** [comment] 2015-09-28 13:55
Yes, ofcourse . My config code:
```
    IMPALA_JDBC_CONFIG = {
        libpath: IMPALA_JAR_HOME + "hive-jdbc.jar",
        libs: [
            IMPALA_JAR_HOME + "hive-service-1.1.0-cdh5.4.2.jar",
            IMPALA_JAR_HOME + "hive-exec-1.1.0-cdh5.4.2.jar",
            IMPALA_JAR_HOME + "libfb303-0.9.2.jar",
            IMPALA_JAR_HOME + "hive-jdbc.jar",
            IMPALA_JAR_HOME + "hive-serde-1.1.0-cdh5.4.2.jar",
            IMPALA_JAR_HOME + "hive-metastore-1.1.0-cdh5.4.2.jar",
            IMPALA_JAR_HOME + "libthrift-0.9.2.jar",

            IMPALA_JAR_HOME + "log4j.jar",
            IMPALA_JAR_HOME + "slf4j-api.jar",
            IMPALA_JAR_HOME + "commons-logging-1.1.3.jar",
            IMPALA_JAR_HOME + "httpclient-4.2.5.jar",
            IMPALA_JAR_HOME + "hadoop-common.jar",
            IMPALA_JAR_HOME + "httpcore-4.2.5.jar"
        ],
        drivername: "org.apache.hive.jdbc.HiveDriver",
        url: "jdbc:hive2://" + IMPALA_HOST + "/;auth=noSasl"
    };
    IMPALA_JDBC_CONFIG = {
        libpath: IMPALA_JAR_HOME + "hive-jdbc.jar",
        libs: [
            IMPALA_JAR_HOME + "hive-service-1.1.0-cdh5.4.2.jar",
            IMPALA_JAR_HOME + "hive-exec-1.1.0-cdh5.4.2.jar",
            IMPALA_JAR_HOME + "libfb303-0.9.2.jar",
            IMPALA_JAR_HOME + "hive-jdbc.jar",
            IMPALA_JAR_HOME + "hive-serde-1.1.0-cdh5.4.2.jar",
            IMPALA_JAR_HOME + "hive-metastore-1.1.0-cdh5.4.2.jar",
            IMPALA_JAR_HOME + "libthrift-0.9.2.jar",

            IMPALA_JAR_HOME + "log4j.jar",
            IMPALA_JAR_HOME + "slf4j-api.jar",
            IMPALA_JAR_HOME + "commons-logging-1.1.3.jar",
            IMPALA_JAR_HOME + "httpclient-4.2.5.jar",
            IMPALA_JAR_HOME + "hadoop-common.jar",
            IMPALA_JAR_HOME + "httpcore-4.2.5.jar"
        ],
        drivername: "org.apache.hive.jdbc.HiveDriver",
        url: "jdbc:hive2://" + IMPALA_HOST + "/;auth=noSasl"
    };

    IMPALA_JDBC_CONFIG = {
        libpath: IMPALA_JAR_HOME + "hive-jdbc.jar",
        libs: [
            IMPALA_JAR_HOME + "hive-service-1.1.0-cdh5.4.2.jar",
            IMPALA_JAR_HOME + "hive-exec-1.1.0-cdh5.4.2.jar",
            IMPALA_JAR_HOME + "libfb303-0.9.2.jar",
            IMPALA_JAR_HOME + "hive-jdbc.jar",
            IMPALA_JAR_HOME + "hive-serde-1.1.0-cdh5.4.2.jar",
            IMPALA_JAR_HOME + "hive-metastore-1.1.0-cdh5.4.2.jar",
            IMPALA_JAR_HOME + "libthrift-0.9.2.jar",

            IMPALA_JAR_HOME + "log4j.jar",
            IMPALA_JAR_HOME + "slf4j-api.jar",
            IMPALA_JAR_HOME + "commons-logging-1.1.3.jar",
            IMPALA_JAR_HOME + "httpclient-4.2.5.jar",
            IMPALA_JAR_HOME + "hadoop-common.jar",
            IMPALA_JAR_HOME + "httpcore-4.2.5.jar"
        ],
        drivername: "org.apache.hive.jdbc.HiveDriver",
        url: "jdbc:hive2://" + IMPALA_HOST + "/;auth=noSasl"
    };
```

**Comment by veve90** [comment] 2015-09-28 13:56
I closed the issue by mistake.

**Comment by veve90** [comment] 2015-10-09 07:35
Do you need any more information?

**Comment by CraZySacX** [comment] 2015-10-12 19:28
I was not able to reproduce this.  However, one of the changes between 0.0.13 and 0.0.15, was the addition of true property support for the config options.  Check out the tests directory for the v0.0.15 branch.  This may be as simple as properly specifying the username/password in the configuration options.

**Comment by veve90** [comment] 2015-10-19 15:42
Hello, I cannot check right now, but I will check later friday. 
However, normally I do not have any username/password..

**Comment by veve90** [comment] 2015-11-04 08:43
I tried to add the user/password (empty or filled in with some values) but I still have the same error.
I also tried to add /remove /change the url by removing the auth=noSasl but it didn't worked..

Do you have other suggestions?

**Comment by CraZySacX** [comment] 2015-11-04 19:42
Try this version of the config (the key part is the user/password in the properties array):

```javascript
var configWithPropertiesInConfig = {
  // Required
  libpath: __dirname + 'path/to/jdbc.jar',
  drivername: 'com.java.driverclass',
  url: 'url/to/database',
  
  // Optional
  libs: [__dirname + 'path/to/other/jars.jar'],
  properties: [
    ['user', 'SA'],
    ['password','']
  ]
};
```

**Comment by veve90** [comment] 2015-11-05 08:43
Hello,I have the same error with this version of the config (authentification in properties)..

**Comment by veve90** [comment] 2015-11-26 08:46
Do you have any other suggestions? Will an update to the last version help us? Thank you!

**Comment by CraZySacX** [comment] 2016-02-05 00:22
Closing in preference to your other issue.  Feel free to reopen if this is still a problem.

**Closed by CraZySacX** 2016-02-05 00:22 UTC
